# Generated by Django 5.2.10 on 2026-02-11 07:05

import core.storage
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useravatar',
            name='original',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=core.storage.UniqueFilePathGenerator('avatars')),
        ),
        migrations.AlterField(
            model_name='useravatar',
            name='thumbnail',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=core.storage.UniqueFilePathGenerator('avatars/thumbnails')),
        ),
    ]
