# Generated by Django 6.0 on 2026-04-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
        ("orders", "0002_order_payment_fields_and_statuses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="payments.paymenttransaction",
            ),
        ),
    ]
