# Generated by Django 5.2.10 on 2026-05-20 10:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_payment_transaction'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='unique_checkout_idempotency_key_per_user',
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('idempotency_key', ''), _negated=True), ('idempotency_key__isnull', False)), fields=('user', 'idempotency_key'), name='unique_checkout_idempotency_key_per_user'),
        ),
    ]
