# Generated by Django 6.0 on 2026-04-06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=32)),
                ('line1', models.CharField(max_length=128)),
                ('line2', models.CharField(blank=True, default='', max_length=128)),
                ('city', models.CharField(max_length=64)),
                ('state', models.CharField(blank=True, default='', max_length=64)),
                ('postal_code', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Enter a valid postal code.', regex='^[A-Za-z0-9\\- ]{3,12}$')])),
                ('country', models.CharField(default='US', max_length=2)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
